<?php
/*
	Usage example for XBMC-PHP. Builds a "wall" using the thumbs from your movie library.
	Make sure you set the connection parameters correctly!
*/

//Include the XBMC-PHP Library
include("xbmc.php");
//Register the classes, configure the connection and connect to the XBMCs...
$xbmcHost = new xbmcHost('change-me');
$xbmcJson = new xbmcJson($xbmcHost);
$xbmcHttp = new xbmcHttp($xbmcHost);
//Done connecting...

//Get movie collection
$moviesRaw = $xbmcJson->VideoLibrary->GetMovies();

//Variables to hold everything...
$movies = array();
$moviesHTML = "";

foreach($moviesRaw->movies as $movie) {
	//Removes "The" from the movies title, for sorting reasons.
	$title = str_replace("The ", "", $movie->label);
	$movies[$title]['id'] = $movie->movieid;
	$movies[$title]['title'] = $movie->label;
	$movies[$title]['filename'] = $movie->file;
	/*
	We need to check certain properties exist before referencing them,
	otherwise a notice will be generated by PHP due to a JSON-RPC error.
	*/
	if(property_exists($movie, 'thumbnail'))
		$movies[$title]['thumbnail'] = $movie->thumbnail;
	if(property_exists($movie, 'fanart'))
		$movies[$title]['fanart'] = $movie->fanart;
}

//Sort the array by movie name (XBMC function that is supposed to do this dosn't seem to do anything!!!)
ksort($movies);

//Display the "movie-wall"
foreach($movies as $movie) {
	$moviesHTML .= "<img src=\"http://".$xbmcHost->url()."/".$xbmcJson->Files->Download($movie['thumbnail'])->path."\" width=\"104\" height=\"156\" title=\"".$movie['title']."\">";
}

//Output some HTML
?>
<html>
	<head>
		<title>My XBMC Movie Collection</title>
		<style type="text/css">
			body {
				margin: 0px;
				background: #000;
			}
		</style>
	</head>
	<body>
	<?php echo $moviesHTML; ?>
	</body>
</html>